sudo: false
language: python
python:
  - "2.7"
branches:
  only: 
    - master
env:
  global:
    - GH_REF: github.com/otamachan/sphinxcontrib-ros.git
    - secure: "ZLU2VH/hIpB6AnS/wmuMNCTjGr6ZYrM2lVLl7BWEk2qUHxM0ItaGrY6nW3JNIrEorvB64X92JNpv2mCRC+N3utkYZfVyyrCwiy6smX/LptdBvQJuqGRKaAq+iZV/yD/DatE3QcfEvMX6Wqhu5UmQFYvfDHF0vStjojDG9LWSdQdeSUNHjJ1gm6xGjh9PGerznCELCG7mXhe2pXwQ2J24aBjhQvR8Gk4L1NfNFUaq/4FfTaWcWym/wIZ1IBLAifydfYEq1UttP3r3lUodA6aiZhzdN0/F0Gz3sHDckc+5pJfOfOeOoSJv8O+QL0HgRmayMbWY6y5WzoKXgnujSbLUwua6Haowp/9jMqX6RvIdEkDLUdOpP9BOeYXPxW/V+HDBzwU6ve1dbUR8nGyGRJXYBwXegadR/Qe1eq842l8C8Zw9qGwF4Ym3GmSpR6i+WHWy1cNXI/C1sxv3j7HFr2DVcO7FtqHzvEqcmEdLPrrI/s4FAXWbj4fvv4Ori9ChhdO03DcBx9OhCK/unQ4adAzelPHCp7XQ2KRQIh9TRlRxsJYs3h1bID3hAttdF7G7kPJSIhdAzthZcDHA8kfdzZA9TLa7tJulwtQgVs09j7/+KDMBnzYdHELXQpasyLdrH8L8dYN0yJzURRFtoikxcc7+hhRnTveIzrRkEX5aGeTKlGs="
install:
  - pip install tox
  - pip install -r requirements.txt
script:
  - tox
  - cd doc
  - make html
after_success:
  - pip install sphinxcontrib-ros
  - cd _build/html
  - git init
  - git add .
  - git config user.name "Travis CI"
  - git config user.email "otamachan@gmail.com"
  - touch .nojekyll
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
